### ISSUE TITLE
Backup Phrase recover

### ISSUE THREAD

**Issue by successhalf** [zhuquanbin/ethereum-bip44#1]
12 word phrase, lowercase, with spaces between each word, to recover funds & transactions.
bulk i can't search by hand
I need a program to input 12 words phrase
output address | Private key
1F5qrDynCi5hXwcmK8XQemiL5jZjczUVtT | L51jsPUMtSH4t9mcdMb56Hff8rH73x5uDapRUMaKR6TcL4RaQPPQ
https://prnt.sc/mrigrn

**Comment by zhuquanbin** [comment]
you can try it.  [HDPrivateKey.master_key_from_seed(Mnemonic.to_seed(n, passphrase))](https://github.com/zhuquanbin/ethereum-bip44/blob/master/eth_bip44/ethbip44.py#L1319)

**Comment by zhuquanbin** [comment]
> 12 word phrase, lowercase, with spaces between each word, to recover funds & transactions.
> bulk i can't search by hand
> I need a program to input 12 words phrase
> output address | Private key
> 1F5qrDynCi5hXwcmK8XQemiL5jZjczUVtT | L51jsPUMtSH4t9mcdMb56Hff8rH73x5uDapRUMaKR6TcL4RaQPPQ
> https://prnt.sc/mrigrn

you can try it.  [HDPrivateKey.master_key_from_seed(Mnemonic.to_seed(n, passphrase))](https://github.com/zhuquanbin/ethereum-bip44/blob/master/eth_bip44/ethbip44.py#L1319)
